version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
