version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo_data:/data/db
    restart: unless-stopped

  api:
    image: api-bot-adv:latest
    build: 
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    command: python3 /app/main.py
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  bot:
    image: bot-adv:latest
    build: 
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - BOT_API_KEY=777000
      - API_URL=http://api
      - API_PORT=8080

volumes:
  mongo_data:
